name: build-release
run-name: ${{ github.workflow }} is to create release wheel file for pypi
on:
  push:
    branches:
      - 'release/[0-9]+.[0-9]+'
      
jobs:
  build-release:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::498127099666:role/WebIdentity-nm-github-actions-only
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - run: | 
             pwd
             sudo apt-get install python3-pip
             pip3 --version
             sudo pip3 install virtualenv
             virtualenv venv
             source venv/bin/activate
             pip install -e .
             sed -i 's/is_release = False/is_release = True/g' src/sparsezoo/version.py
             make -B build
             deactivate
             ls dist/
             aws s3 ls s3://nm-github-actions/
             aws s3 cp dist/*.whl s3://nm-github-actions/sparsezoo/
